# Generated by Django 4.2.9 on 2024-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tire', '0001_initial'),
        ('rim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgcode', models.CharField(max_length=20)),
                ('rims', models.ManyToManyField(to='rim.rim')),
                ('tires', models.ManyToManyField(to='tire.tire')),
            ],
        ),
    ]
