# Generated by Django 4.2.9 on 2024-01-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='axis',
        ),
    ]
