# Generated by Django 4.2.9 on 2024-01-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0002_remove_tire_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='axis',
            field=models.IntegerField(choices=[(1, 'vorne'), (2, 'hinten')], default=1),
            preserve_default=False,
        ),
    ]
