# Generated by Django 4.2.9 on 2024-01-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0003_tire_axis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='axis',
            field=models.IntegerField(choices=[(1, 'Vorne'), (2, 'Hinten')]),
        ),
    ]
