# Generated by Django 4.2.9 on 2024-01-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0004_alter_tire_axis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='tiredimension',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
