# Generated by Django 4.2.9 on 2024-01-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tire', '0005_alter_tire_tiredimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='tiredimension',
            field=models.CharField(max_length=20),
        ),
    ]
