# Generated by Django 4.2.9 on 2024-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rim',
            name='rimdimenesion',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
